### ISSUE TITLE
iron:router routes reloads twice when iron-router-progress added

### ISSUE THREAD

**Issue by tdesc** [Multiply/iron-router-progress#42]
Adding multiply:iron-router-progress to project cause iron:router reactively reload each route twice.
If I remove it, route loads once.
# authenticate: start routing.js  ( onBefore )
# filter: signin routing.js
###### ## GLOBAL onAfterAction ######## ( onAfter global router )
# authenticate: start routing.js
# filter: signin routing.js

**Comment by Nesvet** [comment]
I have that kind of problem too. BUT: if I use fuatsengul's fork (https://github.com/fuatsengul/iron-router-progress/) – everything is fine, no twice reloading.
