### ISSUE TITLE
need less upgrade for meteor 1.2

### ISSUE THREAD

**Issue by acemtp** [Multiply/iron-router-progress#58]
meteor 1.2 use less 2 so it creates a conflict and so we cannot use your lib with meteor 1.2.

    => Errors prevented startup:

       While selecting package versions:
       error: Conflict: Constraint less@1.0.11 is not satisfied by less 2.5.0-rc.3_1.
       Constraints on package "less":
       * less@=2.5.0-rc.3_1 <- top level
       * less@2.5.0-rc.0_1 <- accounts-ui 1.1.6-rc.0
       * less@2.5.0-rc.0_1 <- accounts-ui-unstyled 1.1.8-rc.0 <- accounts-ui 1.1.6-rc.0
       * less@1.0.11 <- multiply:iron-router-progress 1.0.1

**Comment by ryanhanwu** [comment]
+1

**Comment by johnschult** [comment]
+1

**Comment by manuelmateus16** [comment]
+1

**Comment by enam** [comment]
same

**Comment by micahalcorn** [comment]
This is the last one that I'm waiting on. :(

**Comment by sferoze** [comment]
+ 1 :)

**Comment by kroman0** [comment]
+1

**Comment by sebastianconcept** [comment]
+1

**Comment by sunny0825** [comment]
+1

**Comment by sferoze** [comment]
If we download this package into our packages folder, what changes need to be made to package.js to get it to work with meteor 1.2. This could be a temp fix until the update is made. Then after all you have to do is just delete the folder from packages directory.

**Comment by fungilation** [comment]
+1

**Comment by Multiply** [comment]
Please check if the current release works.

**Comment by sferoze** [comment]
Just updated, and it works flawlessly! Thanks

**Comment by Multiply** [comment]
My pleasure, @sferoze - Closing the issue for now. Just reopen it, if you have this specific issue. :)
